# Generated by Django 5.2.5 on 2025-08-31 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=20, unique=True)),
                ("origin", models.CharField(max_length=50)),
                ("destination", models.CharField(max_length=50)),
                ("features", models.TextField()),
                ("starting_time", models.TimeField()),
                ("reach_time", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_numbaer", models.CharField(max_length=10)),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookings.bus"
                    ),
                ),
            ],
        ),
    ]
