# Generated by Django 5.2.5 on 2025-08-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seat",
            old_name="seat_numbaer",
            new_name="seat_number",
        ),
    ]
