# Generated by Django 5.2.5 on 2025-08-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_rename_seat_numbaer_seat_seat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="no_of_seats",
            field=models.PositiveBigIntegerField(default=20),
            preserve_default=False,
        ),
    ]
