# Generated by Django 5.2.5 on 2025-08-31 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bus",
            old_name="starting_time",
            new_name="start_time",
        ),
        migrations.AlterField(
            model_name="bus",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="seat",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="bookings.bus",
            ),
        ),
    ]
