# Generated by Django 5.2.5 on 2025-09-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0005_rename_starting_time_bus_start_time_alter_bus_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "Confirmed"), ("cancelled", "Cancelled")],
                default="confirmed",
                max_length=10,
            ),
        ),
    ]
